# ~/.bash_profile:
#
# bash specific environment variables

if [ -r ~/.profile ]; then 
   . ~/.profile; 
fi

case "$-" in 
   *i*) 
      if [ -r ~/.bashrc ]; then 
         . ~/.bashrc; fi
    ;; 
esac


# Explanations

# Bash startup files loading order
#
# from https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/
#
# For Bash, they work as follows. Read down the appropriate column. Executes A, then B, then C, etc. The B1, B2, B3 means it executes only the first of those files found.
#
#  +----------------+-----------+-----------+------+
#  |                |Interactive|Interactive|Script|
#  |                |login      |non-login  |      |
#  +----------------+-----------+-----------+------+
#  |/etc/profile    |   A       |           |      |
#  +----------------+-----------+-----------+------+
#  |/etc/bash.bashrc|           |    A      |      |
#  +----------------+-----------+-----------+------+
#  |~/.bashrc       |           |    B      |      |
#  +----------------+-----------+-----------+------+
#  |~/.bash_profile |   B1      |           |      |
#  +----------------+-----------+-----------+------+
#  |~/.bash_login   |   B2      |           |      |
#  +----------------+-----------+-----------+------+
#  |~/.profile      |   B3      |           |      |
#  +----------------+-----------+-----------+------+
#  |BASH_ENV        |           |           |  A   |
#  +----------------+-----------+-----------+------+
#  |                |           |           |      |
#  +----------------+-----------+-----------+------+
#  |                |           |           |      |
#  +----------------+-----------+-----------+------+
#  |~/.bash_logout  |    C      |           |      |
#  +----------------+-----------+-----------+------+
