#!/usr/bin/osascript

property theURL : ""

tell application "Safari"

    set theURL to URL of current tab of window 1

end tell

tell application "Google Chrome"

    tell window 1
        make new tab with properties {URL:theURL}
    end tell

    activate

end tell
