#!/bin/bash

# use ssh-add with a password in `xclip -sel clip -o`
USAGE="ssh-add-pass keyfile"

if [ $# -ne 1 ] ; then
  echo "usage: $USAGE"
  exit 1
fi

eval $(ssh-agent)

pass=$(DISPLAY=:0 xclip -sel clip -o)

expect << EOF
  spawn ssh-add $1
  expect "Enter passphrase"
  send "$pass\r"
  expect eof
EOF
