#!/bin/sh


sshkey=$1

[ -n "$sshkey" ] || { echo "usage: $0 <path to sshkey>" ; exit 1; }



ssh-keygen -y -f $sshkey > /dev/null

if [ $? -eq 0 ] ; then
    echo "Password is correct"
    exit  0
else
    echo "Password is not correct"
    exit 1
fi

