#!/bin/sh



# generate the control string
#perl -MDigest::SHA=sha256_base64  -e 'print( sha256_base64($ARGV[0] ))' $@ 
#exit


[ "$1" = '-h' ] && { echo "Usage: $0 salt" ; exit 1; }
[ "$1" = '--help' ] && { echo "Usage: $0 salt" ; exit 1; }

[ "$#" = '0' ] && { 
    read -p "Please enter salt/domain/...: "  salt
    echo 'and now the pw please (pw is then in the clipboard):'

    #perl -MDigest::SHA=sha256_base64 -MTerm::ReadKey -e '$ctrl="8z7uTPFej97+Gvc0i4h/pXQKB6cQ9AQX9autLJXEAAY"; ReadMode "noecho"; $pw = ReadLine 0; chomp $pw;  die "Err: pw not matching!" unless $ctrl eq sha256_base64($pw); print(substr( sha256_base64($pw . ":" . $ARGV[0]), 0,  20))' "$salt" | xclip -sel clip 
    perl -MDigest::SHA=sha256_base64 -MTerm::ReadKey -e '$ctrl="ujwSfdPsRHGLZUqef1Us6C+IRZISUqQ8DkyPhC6p6KE"; ReadMode "noecho"; $pw = ReadLine 0; chomp $pw;  die "Err: pw not matching!" unless $ctrl eq sha256_base64($pw); print(substr( sha256_base64($pw . ":" . $ARGV[0]), 0,  20))' "$salt" | xclip -sel clip 
    exit
}




    #perl -e 'print "go with salt $ENV{SALT}";'

