#!/bin/sh




file=$1
line=$2

[ -n "$line" ] || { echo "usage: file line "; exit 1 ; }


[ -f "$file" ] || { echo "Err: invalid/missing file"; exit 1; }


ln=$(sed -n -e ${line}p "$file")
echo $ln
printf "%s" $ln | xclip -sel clip
