#!/bin/sh

in=$1
n=${in%.*}
out=$n.ml

outf=
if [ -f "$out" ] ; then
   outf=${n}-gen.ml
else
   outf=$out
fi


tmp=$(mktemp)
camlp5 pa_lisp.cmo pr_o.cmo  -impl "$in" > $tmp

if [ "$?" = "0" ] ; then
     cat $tmp | tee $outf
fi
