#!/bin/sh

in=$1
n=${in%.*}
out=$n.ml

camlp5=/Users/bkb/.opam/4.02.3+buckle-master/bin/camlp5

[ -f "$camlp5" ] || {
   camlp5=$(which camlp5)
}
[ -f "$camlp5" ] || {
   echo "Err: couldnt' find camlp5"
   exit 1
}

outf=
if [ -f "$out" ] ; then
   outf=${n}-gen.ml
else
   outf=$out
fi

tmp=$(mktemp)
${camlp5} pa_scheme.cmo pr_o.cmo  -impl "$in" | 
   perl -pe 's/^\s*;\s*(.*)$/$1\n/g'  > $tmp

[ "$?" = "0" ] || {
  echo "Err with camlp5"
   exit 1
 }

if [ "$?" = "0" ] ; then
     cat $tmp | tee $outf
fi

