#!/bin/sh


file=$1

sess=$(tmux display-message -p '#S')

sessbase=${sess%-*}

vimview=$(perl -e "print uc($sessbase . '_view')")

vim --serverlist | grep $vimview > /dev/null || { 
    echo "Err: Vim server $vimview not existing"
    exit 1
}


if [ -n "$file" ] ; then
    view --servername $vimview --remote $1
    tmux resize-pane -t edishell:${sessbase}.2 -x 70
    tmux resize-pane -t edishell:${sssbase}.2 -y 50 
    tmux select-pane -t edishell:${sssbase}.2  
else
    tmux resize-pane -t edishell:${sessbase}.2 -x 70
    tmux resize-pane -t edishell:${sssbase}.2 -y 50 
    tmux select-pane -t edishell:${sssbase}.2  
fi

