export Zshdir=$HOME/.zsh
#aa COMPLETION SETTINGS
# add custom completion scripts
#fpath=(~/.zsh/completion $fpath)
#
#
#
# load configs
for i in checks colors completion exports setopt keys crypto; do
    [ -e $Zshdir/$i.zsh ] && {
        source $Zshdir/$i.zsh
    }


done
 
# compsys initialization
autoload -U compinit
compinit
 
# disable correction
unsetopt correct_all

#export PROMPT_COMMAND='echo -ne "\033]0;${PWD/#$HOME/~}\007"'

#export EDITOR=/usr/local/Cellar/macvim/7.4-73/bin/mvim


# case insitive tab clompletion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# OPAM configuration
. /homes/ben/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

[ -f "$HOME/bins/dotfiles/functions.sh" ] && . $HOME/bins/dotfiles/functions.sh

inc=$HOME/bins/includes
for a in $inc/*  ; do
    [ -e "$a" ] &&  source $a
done

#bindkey -M viins '\C-i' complete-word
#

# Load custimized zsh scripts.
#for config_file (~/.zsh/*.zsh) source $config_file
#
# Faster! (?)
#zstyle ':completion::complete:*' use-cache 1

# case insensitive completion
#zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

#zstyle ':completion:*' verbose yes
#zstyle ':completion:*:descriptions' format '%B%d%b'
#zstyle ':completion:*:messages' format '%d'
#zstyle ':completion:*:warnings' format 'No matches for: %d'
#zstyle ':completion:*' group-name ''
#zstyle ':completion:*' completer _oldlist _expand _force_rehash _complete
#zstyle ':completion:*' completer _expand _force_rehash _complete _approximate _ignored

# generate descriptions with magic.
zstyle ':completion:*' auto-description 'specify: %d'

# Don't prompt for a huge list, page it!
#zstyle ':completion:*:default' list-prompt '%S%M matches%s'

# Don't prompt for a huge list, menu it!
#zstyle ':completion:*:default' menu 'select=2'

# Have the newer files last so I see them first
#zstyle ':completion:*' file-sort modification reverse

# color code completion!!!!  Wohoo!
#zstyle ':completion:*' list-colors "=(#b) #([0-9]#)*=36=31"

#unsetopt LIST_AMBIGUOUS
#setopt  COMPLETE_IN_WORD

# Separate man page sections.  Neat.
#zstyle ':completion:*:manuals' separate-sections true

# Egomaniac!
#zstyle ':completion:*' list-separator 'fREW'

# complete with a menu for xwindow ids
#zstyle ':completion:*:windows' menu on=0
#zstyle ':completion:*:expand:*' tag-order all-expansions

# more errors allowed for large words and fewer for small words
#zstyle ':completion:*:approximate:*' max-errors 'reply=(  $((  ($#PREFIX+$#SUFFIX)/3  ))  )'

# Errors format
#zstyle ':completion:*:corrections' format '%B%d (errors %e)%b'

# # Don't complete stuff already on the line
# zstyle ':completion::*:(rm|vi):*' ignore-line true
# 
# # Don't complete directory we are already in (../here)
# zstyle ':completion:*' ignore-parents parent pwd
# 
# ## Completions
autoload -U compinit
compinit
compinit -C
# #
# ## case-insensitive (all),partial-word and then substring completion
# zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
# #bindkey "^[[A" history-beginning-search-backward
# #bindkey "^[[B" history-beginning-search-forward
# #
# 
# autoload -U up-line-or-beginning-search
# autoload -U down-line-or-beginning-search
# zle -N up-line-or-beginning-search
# zle -N down-line-or-beginning-search
# bindkey "^[[A" up-line-or-beginning-search # Up
# bindkey "^[[B" down-line-or-beginning-search # Down
# 
# 
# 
# 
# #source /homes/ben/.iterm2_shell_integration.zsh
