#!/bin/sh



os=$(uname)


case "$os" in 
   Darwin)
      osascript -e 'tell application "Google Chrome" to reload active tab of window 1'
      ;;
   *)
      echo "Err: not implmented in $os"
      ;;
esac
   
